### ISSUE TITLE
Issue running the console on Chrome in macOS

### ISSUE THREAD

**Issue by thebiglabasky** [terminusdb/terminusdb-bootstrap#15]
**Describe the bug**
Whenever running the bootstrap, the console doesn't seem to be accessible from Chrome, as it warns for a security issue with the self-signed certificate.
I had to open it up on Safari, add the certificate to my keychain and reload to use it from Safari.
If not possible to fix (highly likely) then I guess it would be worth a note for macOS users to go with Safari.

**To Reproduce**
1. Install and run
2. Open https://127.0.0.1:6363
3. Note that Chrome breaks

![image](https://user-images.githubusercontent.com/431257/97921685-92f9b580-1d5b-11eb-84d5-b0a166b4372b.png)

**Expected behavior**
Ideally a way to run the console from Chrome on macOS

**System information (please complete the following information):**
 - OS: macOS
 - Version Catalina 10.15.7
 - Chrome Version 86.0.4240.111 (Official Build) (x86_64)
- How did you run terminus-quickstart?
 Used the command line

**Comment by luke-feeney** [comment]
Thanks for this @thebiglabasky (and great username btw) - we are going to discuss this issue at the next issues and docs triage session in the Discord server. We have been putting in a lot of work (hat tip @rrooij & @dmytri) on the Mac desktop and have 4.0 of the db coming out soon, so we will be trying to clean up all this stuff now. 

Feel free to come along and represent the issue (those who shout loudest get everything!) 

What: Issues and Docs Triage
Where: Discord Server (https://discord.gg/CzE5yZdjpr)
When: Every Thursday from this week until the end of time @ 2pm GMT; 3pm CET; 9am ET; 6am PT; 7.30pm IST

Will report back after anyhow

**Comment by thebiglabasky** [comment]
Nice, thanks!

**Comment by Cheukting** [comment]
@thebiglabasky there is a discussion about it in Discord and hope you have already figured it out already? Let us know and we will provide a workaround if you are still struggling.

**Comment by rrooij** [comment]
You can put `chrome://flags/#allow-insecure-localhost` in your browser and enable the flag. As far as I know, there are no security risks involved. See: https://security.stackexchange.com/questions/241387/chrome-allow-insecure-localhost
