### ISSUE TITLE
Unable to run terminusdb-bootstrap on windows pro

### ISSUE THREAD

**Issue by mukil** [terminusdb/terminusdb-bootstrap#17]
Hey there, I wanted to have a closer look at terminusdb-server and play around with its type building tools (schemas) etc. but despite several attempts I could not get it running on windows. Hope this helps & Cheers!

**Describe the bug**
`terminusdb-bootstrap` does not execute successfully when invoked on win pro `git cmd`, `cmd` or `wsl`

For me, it exits with the errors depicted in the screenshots attached below.

**To Reproduce**
0. Install docker for windows
1. Clone terminusdb-bootstrap on Windows using Git Bash
2. Follow the steps in this repos README

**Expected behavior**
TerminusDB-Server comes up and I can connect to its UI after browsing to `localhost:port`

**Screenshots**

A) Using Docker + Git CMD

![Screenshot 2020-12-16 115744](https://user-images.githubusercontent.com/350005/102698302-aa71fc80-423c-11eb-908e-07becd6757b9.jpg)

B) After installing WSL2 and Debian I can call that directly from Git CMD

![Screenshot 2020-12-16 120033](https://user-images.githubusercontent.com/350005/102698324-c83f6180-423c-11eb-85f5-6cdf6220fb71.jpg)
 
C) Invoking the script from the "wsl" command line leads to the same errors as invoking `bash`

![Uploading Screenshot 2020-12-16 142254.jpg…]()

**System information (please complete the following information):**
 - OS: Windows
 - Version: Pro x64
- How did you run terminus-bootstrap?
- Using (a) `git bash`, using (b) windows `cmd` and (c) using a debian shell provided by wsl2.

**Additional context**
Invoking only `docker` did fetch the terminusdb-server image. See

![Screenshot 2020-12-16 142402](https://user-images.githubusercontent.com/350005/102698436-73501b00-423d-11eb-8e51-0907cf298a8c.jpg)

Running the docker container seems also to work fine using the docker windows gui. So, i am nearly there to getting the server running, or it is running, I guess but without env-variables so I can't connect to the services running inside, i guess.

Just wanted to report this. It is not urgent. I may try this again on a unix machine but I would appreciate any help to get it running on this one, too.

Thanks & I hope this helps.

**Comment by rrooij** [comment]
Hey @mukil I see in your first screenshot that you're using Git CMD instead of Git Bash. Can you try it with Git Bash instead?

**Comment by mukil** [comment]
Thanks for your support on this issue. Indeed, that solved my issue. I assumed `Git CMD` is the `Git Bash` but it is obviously not... Thanks for your help! From my perspective we can close the issue, then.

**Comment by rrooij** [comment]
Glad I could help! And thank you for reporting this issue in such great detail.
