### ISSUE TITLE
Cardinality remains in the schema after removal but does not show in the UI

### ISSUE THREAD

**Issue by MrRaymondLee** [terminusdb/terminusdb-bootstrap#19]
**Describe the bug**
After removing cardinality by deleting the number in the field and saving the schema, the cardinality no longer shows up when viewing the properties but when looking at the schema the cardinality still exists.  

**To Reproduce**
1. Create a cardinality (doesn't matter where and doesn't matter if a min or max)
2. Save the schema
3. Delete the number(s) in the cardinality field(s) that you created in #1
4. Save the schema
5. Look a the property.  No cardinality will be shown as I believe is the correct approach
6. Look at the schema.  Cardinality is still there.

**Expected behavior**
Cardinality to be gone from the schema after deleting the cardinality numbers.

**System information (please complete the following information):**
 - OS: Ubuntu 20
 - Version 4.1.1 on server 4.1.0 (docker)
- How did you run terminus-quickstart? 
- Docker

**Comment by spl** [comment]
Hi! Sorry for the delayed response. We're currently working on a new document API, and we won't have the cardinality in the same way. It should be even easier!
