### ISSUE TITLE
`./terminusdb-container run` unnecessarily asks for root when using iTerm

### ISSUE THREAD

**Issue by AndrewO** [terminusdb/terminusdb-bootstrap#8]
**Describe the bug**

Running `./terminusdb-container run` causes `sudo docker` to prompt for a password on a Mac when using iTerm as a Terminal. However, `sudo` is not necessary for running `docker`, as indicated by the checks in the script for `"$OSTYPE" == "darwin" || "$TERM_PROGRAM" == "Apple_Terminal"`. This fails to match because `TERM_PROGRAM=iTerm.app`.

There are other Terminal emulators for macOS, so just adding this to the `if` is not a good solution. Maybe use `uname` instead?

```
$ uname
Darwin
```

**To Reproduce**
1. Install [iTerm](https://www.iterm2.com/)
2. Run `./terminusdb-container run`

**Expected behavior**

Runs without needing root privileges.

**System information (please complete the following information):**
 - OS: macOS
 - Version: 10.14.6
- How did you run terminus-quickstart? `./terminusdb-container run`

**Workaround**

```
$ TERMINUSDB_DOCKER=docker ./terminusdb-container run
```

**Comment by rrooij** [comment]
You are absolutely right. I think that making use of `uname` makes sense.
